name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Vite project
      - name: Build project
        run: npm run build

      # 5. Controllo dei file buildati
      - name: List build output
        run: ls -la ./dist

      # 6. Deploy su GitHub Pages usando gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
          # opzioni aggiuntive facoltative:
          # user_name: 'github-actions'
          # user_email: 'github-actions@github.com'
